[versions]
project = "4.2.2.0-SNAPSHOT"

kotlin = "2.2.0"

nal-agl = "4.2.2.0-SNAPSHOT"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
korlibs = "6.0.2"
kotest = "5.9.1"

[libraries]
nal-agl-processor = { module = "net.akehurst.language:agl-processor", version.ref = "nal-agl" }
korlibs-korio = { module = "com.soywiz:korlibs-io", version.ref = "korlibs" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
